platform :ios, '15.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example

  #pod 'QiscusMultichannelWidget', '~> 2.2.1'
  pod 'QiscusMultichannelWidget', :path => '../../'
  #pod 'QiscusCore', :path => '../../../../SDKV3/QiscusCore-iOS/'
  pod 'Localize-Swift', '~> 3.2'
end

# Xcode 26+ only supports deployment targets >= 15.0. Several pods still
# declare 9.0/10.0/12.0 in their podspec, so force every generated target
# (including resource bundles) up to the minimum supported version.
IOS_DEPLOYMENT_TARGET = '15.0'

post_install do |installer|
  projects = [installer.pods_project] + installer.generated_projects
  projects.compact.uniq.each do |project|
    project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_DEPLOYMENT_TARGET
    end

    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_DEPLOYMENT_TARGET
      end
    end
  end
end
